-- Run only against the isolated Cloudflare staging Neon branch.
-- These additions preserve historical employee references and provide stable
-- numeric request identifiers for the existing admin frontend.

ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE missed_punch_requests
  ADD COLUMN IF NOT EXISTS request_type varchar(40) NOT NULL DEFAULT 'Missed Clock Out';

ALTER TABLE missed_punch_requests
  ADD COLUMN IF NOT EXISTS admin_row_number bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS missed_punch_admin_row_number_idx
  ON missed_punch_requests (admin_row_number);

CREATE INDEX IF NOT EXISTS employees_visible_name_idx
  ON employees (active, name)
  WHERE deleted_at IS NULL;
